package org.communitypoke.fdroidai.ai.agent

import kotlinx.coroutines.delay

/**
 * On-device fallback used when no agent SDK credentials are configured. It
 * deterministically assembles a userscript scaffold from keywords in the
 * prompt — the same "demo mode" convention as `MockAiSearchProvider` — so the
 * userscript builder works end-to-end offline.
 */
class MockAgentProvider : AgentSdkProvider {

    override val sdk = AgentSdk.MOCK
    override val name = "On-device agent (demo)"
    override val isConfigured = true

    override suspend fun run(request: AgentRequest): AgentResult {
        delay(400) // simulate generation latency so the loading state is visible
        return AgentResult(
            text = generateUserscript(request.prompt),
            providerName = name,
            sdk = sdk,
            turns = 1,
            stopReason = "demo",
        )
    }

    internal fun generateUserscript(prompt: String): String {
        val lower = prompt.lowercase()
        val scriptName = lower.split(Regex("[^a-z0-9]+"))
            .filter { it.length >= 3 }
            .take(4)
            .joinToString(" ")
            .replaceFirstChar { it.uppercaseChar() }
            .ifBlank { "Custom Script" }
        val header = """
            |// ==UserScript==
            |// @name        $scriptName
            |// @namespace   org.communitypoke.fdroidai
            |// @version     1.0
            |// @description ${prompt.replace(Regex("\\s+"), " ").trim().take(120)}
            |// @match       *://*/*
            |// @run-at      document-end
            |// @grant       none
            |// ==/UserScript==
            |
        """.trimMargin()

        val body = when {
            "dark" in lower || "theme" in lower -> """
                |// Applies a dark theme override to every page.
                |const style = document.createElement('style');
                |style.textContent = `
                |  html { background: #121212 !important; }
                |  body { background: #121212 !important; color: #e0e0e0 !important; }
                |  a { color: #80cbc4 !important; }
                |`;
                |document.documentElement.appendChild(style);
                |""".trimMargin()

            listOf("hide", "remove", "block").any { it in lower } -> {
                val selector = QUOTED.find(prompt)?.groupValues?.get(1) ?: ".ad, [class*='ad-']"
                """
                |// Removes matching elements as they appear.
                |const SELECTOR = ${selector.jsLiteral()};
                |const sweep = () => document.querySelectorAll(SELECTOR)
                |  .forEach(el => el.remove());
                |sweep();
                |new MutationObserver(sweep)
                |  .observe(document.documentElement, { childList: true, subtree: true });
                |""".trimMargin()
            }

            "button" in lower || "shortcut" in lower -> """
                |// Adds a floating action button to the page.
                |const btn = document.createElement('button');
                |btn.textContent = '★';
                |Object.assign(btn.style, {
                |  position: 'fixed', bottom: '16px', right: '16px', zIndex: 99999,
                |  padding: '12px', borderRadius: '50%', fontSize: '18px',
                |});
                |btn.addEventListener('click', () => window.scrollTo({ top: 0, behavior: 'smooth' }));
                |document.body.appendChild(btn);
                |""".trimMargin()

            else -> """
                |// Scaffold generated by the on-device demo agent.
                |// Edit this body or configure CLAUDE_API_KEY / CODEX_API_KEY for
                |// full AI-generated scripts.
                |console.log('[userscript] $scriptName loaded on', location.href);
                |""".trimMargin()
        }
        return header + body + "\n"
    }

    private fun String.jsLiteral(): String =
        "'" + replace("\\", "\\\\").replace("'", "\\'") + "'"

    private companion object {
        val QUOTED = Regex("[\"']([^\"']+)[\"']")
    }
}
